//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiShell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuiShell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter cancelled after {0} {1}.
        /// </summary>
        internal static string FilterCancelledMsg {
            get {
                return ResourceManager.GetString("FilterCancelledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter ended with an error after {0} {1}, sorry....
        /// </summary>
        internal static string FilterErrorMsg {
            get {
                return ResourceManager.GetString("FilterErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string HoursStr {
            get {
                return ResourceManager.GetString("HoursStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image cleared..
        /// </summary>
        internal static string ImgClearedMsg {
            get {
                return ResourceManager.GetString("ImgClearedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image closed..
        /// </summary>
        internal static string ImgClosedMsg {
            get {
                return ResourceManager.GetString("ImgClosedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image set to {0} ({1} x {2} pixels)..
        /// </summary>
        internal static string ImgSetMsg {
            get {
                return ResourceManager.GetString("ImgSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string MillisecondsStr {
            get {
                return ResourceManager.GetString("MillisecondsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MinutesStr {
            get {
                return ResourceManager.GetString("MinutesStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled after {0} {1}.
        /// </summary>
        internal static string OperationCancelledMsg {
            get {
                return ResourceManager.GetString("OperationCancelledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation ended with an error after {0} {1}, sorry....
        /// </summary>
        internal static string OperationErrorMsg {
            get {
                return ResourceManager.GetString("OperationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rolling_ball {
            get {
                object obj = ResourceManager.GetObject("rolling_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling ball operation completed! (only took {0} {1}).
        /// </summary>
        internal static string RollingBallEndMsg {
            get {
                return ResourceManager.GetString("RollingBallEndMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal region is the rectangle {0}..
        /// </summary>
        internal static string RollingBallOutputMsg {
            get {
                return ResourceManager.GetString("RollingBallOutputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get the ball rolling (with a window size of {0})....
        /// </summary>
        internal static string RollingBallStartMsg {
            get {
                return ResourceManager.GetString("RollingBallStartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SecondsStr {
            get {
                return ResourceManager.GetString("SecondsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap watercolor {
            get {
                object obj = ResourceManager.GetObject("watercolor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watercolor filter completed! (only took {0} {1}).
        /// </summary>
        internal static string WatercolorEndMsg {
            get {
                return ResourceManager.GetString("WatercolorEndMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning watercolor filter with a window size of {0}....
        /// </summary>
        internal static string WatercolorStartMsg {
            get {
                return ResourceManager.GetString("WatercolorStartMsg", resourceCulture);
            }
        }
    }
}
